require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ChalengesController do

  # This should return the minimal set of attributes required to create a valid
  # Chalenge. As you add validations to Chalenge, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all chalenges as @chalenges" do
      chalenge = Chalenge.create! valid_attributes
      get :index
      assigns(:chalenges).should eq([chalenge])
    end
  end

  describe "GET show" do
    it "assigns the requested chalenge as @chalenge" do
      chalenge = Chalenge.create! valid_attributes
      get :show, :id => chalenge.id.to_s
      assigns(:chalenge).should eq(chalenge)
    end
  end

  describe "GET new" do
    it "assigns a new chalenge as @chalenge" do
      get :new
      assigns(:chalenge).should be_a_new(Chalenge)
    end
  end

  describe "GET edit" do
    it "assigns the requested chalenge as @chalenge" do
      chalenge = Chalenge.create! valid_attributes
      get :edit, :id => chalenge.id.to_s
      assigns(:chalenge).should eq(chalenge)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Chalenge" do
        expect {
          post :create, :chalenge => valid_attributes
        }.to change(Chalenge, :count).by(1)
      end

      it "assigns a newly created chalenge as @chalenge" do
        post :create, :chalenge => valid_attributes
        assigns(:chalenge).should be_a(Chalenge)
        assigns(:chalenge).should be_persisted
      end

      it "redirects to the created chalenge" do
        post :create, :chalenge => valid_attributes
        response.should redirect_to(Chalenge.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved chalenge as @chalenge" do
        # Trigger the behavior that occurs when invalid params are submitted
        Chalenge.any_instance.stub(:save).and_return(false)
        post :create, :chalenge => {}
        assigns(:chalenge).should be_a_new(Chalenge)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Chalenge.any_instance.stub(:save).and_return(false)
        post :create, :chalenge => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested chalenge" do
        chalenge = Chalenge.create! valid_attributes
        # Assuming there are no other chalenges in the database, this
        # specifies that the Chalenge created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Chalenge.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => chalenge.id, :chalenge => {'these' => 'params'}
      end

      it "assigns the requested chalenge as @chalenge" do
        chalenge = Chalenge.create! valid_attributes
        put :update, :id => chalenge.id, :chalenge => valid_attributes
        assigns(:chalenge).should eq(chalenge)
      end

      it "redirects to the chalenge" do
        chalenge = Chalenge.create! valid_attributes
        put :update, :id => chalenge.id, :chalenge => valid_attributes
        response.should redirect_to(chalenge)
      end
    end

    describe "with invalid params" do
      it "assigns the chalenge as @chalenge" do
        chalenge = Chalenge.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Chalenge.any_instance.stub(:save).and_return(false)
        put :update, :id => chalenge.id.to_s, :chalenge => {}
        assigns(:chalenge).should eq(chalenge)
      end

      it "re-renders the 'edit' template" do
        chalenge = Chalenge.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Chalenge.any_instance.stub(:save).and_return(false)
        put :update, :id => chalenge.id.to_s, :chalenge => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested chalenge" do
      chalenge = Chalenge.create! valid_attributes
      expect {
        delete :destroy, :id => chalenge.id.to_s
      }.to change(Chalenge, :count).by(-1)
    end

    it "redirects to the chalenges list" do
      chalenge = Chalenge.create! valid_attributes
      delete :destroy, :id => chalenge.id.to_s
      response.should redirect_to(chalenges_url)
    end
  end

end
