require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CompetitionsController do

  # This should return the minimal set of attributes required to create a valid
  # Competition. As you add validations to Competition, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all competitions as @competitions" do
      competition = Competition.create! valid_attributes
      get :index
      assigns(:competitions).should eq([competition])
    end
  end

  describe "GET show" do
    it "assigns the requested competition as @competition" do
      competition = Competition.create! valid_attributes
      get :show, :id => competition.id.to_s
      assigns(:competition).should eq(competition)
    end
  end

  describe "GET new" do
    it "assigns a new competition as @competition" do
      get :new
      assigns(:competition).should be_a_new(Competition)
    end
  end

  describe "GET edit" do
    it "assigns the requested competition as @competition" do
      competition = Competition.create! valid_attributes
      get :edit, :id => competition.id.to_s
      assigns(:competition).should eq(competition)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Competition" do
        expect {
          post :create, :competition => valid_attributes
        }.to change(Competition, :count).by(1)
      end

      it "assigns a newly created competition as @competition" do
        post :create, :competition => valid_attributes
        assigns(:competition).should be_a(Competition)
        assigns(:competition).should be_persisted
      end

      it "redirects to the created competition" do
        post :create, :competition => valid_attributes
        response.should redirect_to(Competition.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved competition as @competition" do
        # Trigger the behavior that occurs when invalid params are submitted
        Competition.any_instance.stub(:save).and_return(false)
        post :create, :competition => {}
        assigns(:competition).should be_a_new(Competition)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Competition.any_instance.stub(:save).and_return(false)
        post :create, :competition => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested competition" do
        competition = Competition.create! valid_attributes
        # Assuming there are no other competitions in the database, this
        # specifies that the Competition created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Competition.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => competition.id, :competition => {'these' => 'params'}
      end

      it "assigns the requested competition as @competition" do
        competition = Competition.create! valid_attributes
        put :update, :id => competition.id, :competition => valid_attributes
        assigns(:competition).should eq(competition)
      end

      it "redirects to the competition" do
        competition = Competition.create! valid_attributes
        put :update, :id => competition.id, :competition => valid_attributes
        response.should redirect_to(competition)
      end
    end

    describe "with invalid params" do
      it "assigns the competition as @competition" do
        competition = Competition.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Competition.any_instance.stub(:save).and_return(false)
        put :update, :id => competition.id.to_s, :competition => {}
        assigns(:competition).should eq(competition)
      end

      it "re-renders the 'edit' template" do
        competition = Competition.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Competition.any_instance.stub(:save).and_return(false)
        put :update, :id => competition.id.to_s, :competition => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested competition" do
      competition = Competition.create! valid_attributes
      expect {
        delete :destroy, :id => competition.id.to_s
      }.to change(Competition, :count).by(-1)
    end

    it "redirects to the competitions list" do
      competition = Competition.create! valid_attributes
      delete :destroy, :id => competition.id.to_s
      response.should redirect_to(competitions_url)
    end
  end

end
