require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EvaluatorsController do

  # This should return the minimal set of attributes required to create a valid
  # Evaluator. As you add validations to Evaluator, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all evaluators as @evaluators" do
      evaluator = Evaluator.create! valid_attributes
      get :index
      assigns(:evaluators).should eq([evaluator])
    end
  end

  describe "GET show" do
    it "assigns the requested evaluator as @evaluator" do
      evaluator = Evaluator.create! valid_attributes
      get :show, :id => evaluator.id.to_s
      assigns(:evaluator).should eq(evaluator)
    end
  end

  describe "GET new" do
    it "assigns a new evaluator as @evaluator" do
      get :new
      assigns(:evaluator).should be_a_new(Evaluator)
    end
  end

  describe "GET edit" do
    it "assigns the requested evaluator as @evaluator" do
      evaluator = Evaluator.create! valid_attributes
      get :edit, :id => evaluator.id.to_s
      assigns(:evaluator).should eq(evaluator)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Evaluator" do
        expect {
          post :create, :evaluator => valid_attributes
        }.to change(Evaluator, :count).by(1)
      end

      it "assigns a newly created evaluator as @evaluator" do
        post :create, :evaluator => valid_attributes
        assigns(:evaluator).should be_a(Evaluator)
        assigns(:evaluator).should be_persisted
      end

      it "redirects to the created evaluator" do
        post :create, :evaluator => valid_attributes
        response.should redirect_to(Evaluator.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved evaluator as @evaluator" do
        # Trigger the behavior that occurs when invalid params are submitted
        Evaluator.any_instance.stub(:save).and_return(false)
        post :create, :evaluator => {}
        assigns(:evaluator).should be_a_new(Evaluator)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Evaluator.any_instance.stub(:save).and_return(false)
        post :create, :evaluator => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested evaluator" do
        evaluator = Evaluator.create! valid_attributes
        # Assuming there are no other evaluators in the database, this
        # specifies that the Evaluator created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Evaluator.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => evaluator.id, :evaluator => {'these' => 'params'}
      end

      it "assigns the requested evaluator as @evaluator" do
        evaluator = Evaluator.create! valid_attributes
        put :update, :id => evaluator.id, :evaluator => valid_attributes
        assigns(:evaluator).should eq(evaluator)
      end

      it "redirects to the evaluator" do
        evaluator = Evaluator.create! valid_attributes
        put :update, :id => evaluator.id, :evaluator => valid_attributes
        response.should redirect_to(evaluator)
      end
    end

    describe "with invalid params" do
      it "assigns the evaluator as @evaluator" do
        evaluator = Evaluator.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Evaluator.any_instance.stub(:save).and_return(false)
        put :update, :id => evaluator.id.to_s, :evaluator => {}
        assigns(:evaluator).should eq(evaluator)
      end

      it "re-renders the 'edit' template" do
        evaluator = Evaluator.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Evaluator.any_instance.stub(:save).and_return(false)
        put :update, :id => evaluator.id.to_s, :evaluator => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested evaluator" do
      evaluator = Evaluator.create! valid_attributes
      expect {
        delete :destroy, :id => evaluator.id.to_s
      }.to change(Evaluator, :count).by(-1)
    end

    it "redirects to the evaluators list" do
      evaluator = Evaluator.create! valid_attributes
      delete :destroy, :id => evaluator.id.to_s
      response.should redirect_to(evaluators_url)
    end
  end

end
